# Generated by Django 4.0.2 on 2022-06-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdata',
            name='cycle_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
