# Generated by Django 4.0.2 on 2022-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_workdata_cycle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdata',
            name='cycle_time',
            field=models.FloatField(),
        ),
    ]
