# Generated by Django 4.0.2 on 2022-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_workdata_cycle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfloor',
            name='Freeze_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shopfloor',
            name='Ranking',
            field=models.DateField(),
        ),
    ]
