# Generated by Django 4.0.5 on 2022-06-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shopfloor_freeze_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfloor',
            name='smoothing_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
