# Generated by Django 4.0.5 on 2022-06-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shopfloor_smoothing_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfloor',
            name='closed',
            field=models.BooleanField(null=True),
        ),
    ]
