# Generated by Django 4.0.5 on 2022-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shopfloor_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarconfigurationcpordo',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calendarconfigurationtreatement',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coois',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='holidayscalendar',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shopfloor',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workdata',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zpp',
            name='deleted_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
