# Generated by Django 4.0.5 on 2022-07-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_calendarconfigurationcpordo_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Profit_center',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
