# Generated by Django 4.0.5 on 2022-07-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cycle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
