# Generated by Django 4.0.5 on 2022-07-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='division_name',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='cycle',
            old_name='date',
            new_name='work_day',
        ),
    ]
