# Generated by Django 4.0.5 on 2022-07-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_division_name_cycle_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdata',
            name='cycle_time',
        ),
    ]
