# Generated by Django 4.0.5 on 2022-08-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cycle_workdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='owner',
            field=models.CharField(default='officiel', max_length=30),
        ),
    ]
