# Generated by Django 4.0.5 on 2022-08-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cycle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
