# Generated by Django 4.0.5 on 2022-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_cycle_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfloor',
            name='shared',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='shopfloor',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
