# Generated by Django 4.0.5 on 2022-10-26 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0017_shopfloor_shared_shopfloor_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(max_length=30, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('restored_at', models.DateTimeField(auto_now=True, null=True)),
                ('restored_by', models.CharField(default='Marwa', max_length=30, null=True)),
                ('function', models.CharField(max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.division')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model),
        ),
    ]
