# Generated by Django 4.0.5 on 2022-11-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_zpp_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='coois',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
