# Generated by Django 4.0.5 on 2022-11-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_coois_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopfloor',
            name='shared',
        ),
        migrations.AddField(
            model_name='shopfloor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
