# Generated by Django 4.0.5 on 2022-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_shopfloor_planning_approval_shopfloor_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapproval',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
