# Generated by Django 4.0.5 on 2022-12-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_planningapproval_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='planning_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.planningapproval'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
