# Generated by Django 4.0.5 on 2023-02-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cycle_planning_approval_cycle_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='shared',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
