# Generated by Django 4.0.5 on 2023-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_cycle_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle_time',
            field=models.FloatField(null=True),
        ),
    ]
