# Generated by Django 4.0.5 on 2023-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_cycle_cycle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.IntegerField(unique=True),
        ),
    ]
